import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--enable-unsafe-swiftshader', '--mute-audio', '--disable-gpu'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('pageerror', e => errors.push(String(e).slice(0, 200)));
await page.goto('file:///home/user/vox-arena/release/index.html');
await page.waitForFunction('window.__VOX__ && window.__VOX__.ready', null, { timeout: 30000 });
console.log('1: ready');
await page.evaluate('window.__VOX__.start(); window.__VOX__.gfx.pixelScale(0.2)');
await page.waitForFunction('window.__VOX__.waves.num === 1', null, { timeout: 60000 });
console.log('2: волна 1');
await page.waitForTimeout(1000);
await page.evaluate(`(() => { const V = window.__VOX__; V.player.hp = 0.5; for (let i=0;i<4;i++) V.spawn('minion', (i-1.5)*0.7, -1.2); })()`);
await page.waitForFunction(`window.__VOX__.state === 'dead'`, null, { timeout: 60000 });
console.log('3: мёртв');
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/w0-death.png' });
await page.click('#btn-restart');
console.log('4: клик рестарт');
await page.waitForTimeout(300);
await page.screenshot({ path: 'shots/w0-r03.png' });
await page.waitForTimeout(600);
await page.screenshot({ path: 'shots/w0-r09.png' });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/w0-r24.png' });
console.log('5: скрины сняты, state =', await page.evaluate('window.__VOX__.state'));
// второй цикл
await page.waitForFunction('window.__VOX__.waves.num >= 1', null, { timeout: 90000 });
await page.waitForTimeout(800);
await page.evaluate(`(() => { const V = window.__VOX__; V.player.hp = 0.4; for (let i=0;i<4;i++) V.spawn('minion', (i-1.5)*0.7, -1.2); })()`);
await page.waitForFunction(`window.__VOX__.state === 'dead'`, null, { timeout: 60000 });
await page.waitForTimeout(1500);
await page.click('#btn-restart');
await page.waitForTimeout(500);
await page.screenshot({ path: 'shots/w1-r05.png' });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/w1-r20.png' });
console.log('6: цикл 2 done');
console.log('errors:', errors.length ? errors.slice(0, 3) : 'нет');
await browser.close();
